package client

var (
	//100个指标
	MetricNames = [...]string{
		"tomcat_cup_usage_persent",
		"tomcat_cup_idle_persent",
		"tomcat_menory_usage_persent",
		"tomcat_menory_idle_persent",
		"tomcat_disk_usage_persent",
		"tomcat_disk_idle_persent",
		"tomcat_io_usage_persent",
		"tomcat_io_idle_persent",
		"tomcat_network_usage_persent",
		"tomcat_network_idle_persent",

		"iis_cup_usage_persent",
		"iis_cup_idle_persent",
		"iis_menory_usage_persent",
		"iis_menory_idle_persent",
		"iis_disk_usage_persent",
		"iis_disk_idle_persent",
		"iis_io_usage_persent",
		"iis_io_idle_persent",
		"iis_network_usage_persent",
		"iis_network_idle_persent",

		"node_cup_usage_persent",
		"node_cup_idle_persent",
		"node_menory_usage_persent",
		"node_menory_idle_persent",
		"node_disk_usage_persent",
		"node_disk_idle_persent",
		"node_io_usage_persent",
		"node_io_idle_persent",
		"node_network_usage_persent",
		"node_network_idle_persent",

		"was_cup_usage_persent",
		"was_cup_idle_persent",
		"was_menory_usage_persent",
		"was_menory_idle_persent",
		"was_disk_usage_persent",
		"was_disk_idle_persent",
		"was_io_usage_persent",
		"was_io_idle_persent",
		"was_network_usage_persent",
		"was_network_idle_persent",

		"container_cup_usage_persent",
		"container_cup_idle_persent",
		"container_menory_usage_persent",
		"container_menory_idle_persent",
		"container_disk_usage_persent",
		"container_disk_idle_persent",
		"container_io_usage_persent",
		"container_io_idle_persent",
		"container_network_usage_persent",
		"container_network_idle_persent",

		"consul_cup_usage_persent",
		"consul_cup_idle_persent",
		"consul_menory_usage_persent",
		"consul_menory_idle_persent",
		"consul_disk_usage_persent",
		"consul_disk_idle_persent",
		"consul_io_usage_persent",
		"consul_io_idle_persent",
		"consul_network_usage_persent",
		"consul_network_idle_persent",

		"mq_cup_usage_persent",
		"mq_cup_idle_persent",
		"mq_menory_usage_persent",
		"mq_menory_idle_persent",
		"mq_disk_usage_persent",
		"mq_disk_idle_persent",
		"mq_io_usage_persent",
		"mq_io_idle_persent",
		"mq_network_usage_persent",
		"mq_network_idle_persent",

		"mb_cup_usage_persent",
		"mb_cup_idle_persent",
		"mb_menory_usage_persent",
		"mb_menory_idle_persent",
		"mb_disk_usage_persent",
		"mb_disk_idle_persent",
		"mb_io_usage_persent",
		"mb_io_idle_persent",
		"mb_network_usage_persent",
		"mb_network_idle_persent",

		"url_cup_usage_persent",
		"url_cup_idle_persent",
		"url_menory_usage_persent",
		"url_menory_idle_persent",
		"url_disk_usage_persent",
		"url_disk_idle_persent",
		"url_io_usage_persent",
		"url_io_idle_persent",
		"url_network_usage_persent",
		"url_network_idle_persent",

		"port_cup_usage_persent",
		"port_cup_idle_persent",
		"port_menory_usage_persent",
		"port_menory_idle_persent",
		"port_disk_usage_persent",
		"port_disk_idle_persent",
		"port_io_usage_persent",
		"port_io_idle_persent",
		"port_network_usage_persent",
		"port_network_idle_persent",
	}
	MetricNamesLen = len(MetricNames)

	HostnameLabel = "hostname"
	Hostnames     = [...]string{
		"dgg-1-",
		"dgg-2-",
		"dgg-3-",
		"dgg-4-",
		"nkg-1-",
		"nkg-2-",
		"nkg-3-",
		"szx-1-",
		"szx-2-",
		"szx-3-",
	}
	HostnamesLen = len(Hostnames)

	Tags = map[string]string{
		"domain":       "qq",
		"containerid":  "container_a",
		"quality":      "0.25",
		"env_location": "dgg",
		"cpu":          "cpu1",
		"disk":         "disk1",
	}
)
